# Generated by Django 3.2.16 on 2022-12-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Encontreiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('idade', models.CharField(max_length=3, verbose_name='Idade')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('estado_civil', models.CharField(max_length=40, verbose_name='Estado civil')),
                ('cep_encontreiro', models.CharField(max_length=11, verbose_name='CEP')),
                ('logradouro_encontreiro', models.CharField(max_length=40, verbose_name='Logradouro')),
                ('numero_encontreiro', models.CharField(max_length=10, null=True, verbose_name='Numero')),
                ('complemento_encontreiro', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('bairro_encontreiro', models.CharField(max_length=40, verbose_name='Bairro')),
                ('estado_encontreiro', models.CharField(max_length=26, verbose_name='Estado')),
                ('cidade_encontreiro', models.CharField(max_length=30, verbose_name='Cidade')),
                ('frequentando_igreja_enc', models.BooleanField(verbose_name='Está frequentando a igreja?')),
                ('nome_igreja', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da igreja')),
                ('pessoa_convite_enc', models.CharField(max_length=60, verbose_name='Padrinho ou madrinha')),
                ('ano_participacao', models.IntegerField(verbose_name='Ano de participação')),
                ('equipes_trab', models.CharField(max_length=255, verbose_name='Equipes que já trabalhou')),
                ('qtd_participacoes', models.IntegerField(verbose_name='Quantidade de participações')),
                ('status', models.IntegerField(choices=[(0, 'Aguardando Pagamento'), (1, 'Concluída'), (2, 'Cancelada')], default=0, verbose_name='Situação')),
                ('doenca_cardiaca', models.BooleanField(default=False, verbose_name='Possui doença cardíaca?')),
                ('diabetico', models.BooleanField(default=False, verbose_name='É diabético')),
                ('hipertenso', models.BooleanField(default=False, verbose_name='É hipertenso')),
                ('data_cadastro', models.DateTimeField(auto_now=True, verbose_name='Inscrito em')),
                ('observacoes_gerais', models.TextField(null=True, verbose_name='Observações Gerais')),
            ],
        ),
        migrations.CreateModel(
            name='Encontrista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_apelido', models.CharField(max_length=60, null=True, verbose_name='Nome apelido')),
                ('data_nascimento_enc', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('celular', models.CharField(max_length=15, null=True, verbose_name='Celular')),
                ('estado_civil', models.CharField(max_length=40, null=True, verbose_name='Estado civil')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=40, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, null=True, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bairro')),
                ('estado', models.CharField(max_length=4, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=30, null=True, verbose_name='Cidade')),
                ('naturalidade', models.CharField(max_length=50, null=True, verbose_name='Naturalidade')),
                ('frequenta_igreja', models.BooleanField(verbose_name='Está frequentando alguma igreja?')),
                ('religiao', models.CharField(max_length=30, null=True, verbose_name='Religião')),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do pai')),
                ('religiao_pai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Religião do pai')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da mãe')),
                ('religiao_mae', models.CharField(blank=True, max_length=30, null=True, verbose_name='Religião da mãe')),
                ('possui_automovel', models.BooleanField(verbose_name='Possui automóvel?')),
                ('pessoas_moradia', models.CharField(max_length=70, null=True, verbose_name='Quem mora na mesma residência')),
                ('pessoas_participando', models.CharField(max_length=5, null=True, verbose_name='Algum conhecido participando do programa?')),
                ('nome_pessoas_participando', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome das pessoas')),
                ('alergia', models.BooleanField(verbose_name='Possui algum tipo de alergia?')),
                ('nome_alergia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qual alergia?')),
                ('diabetico', models.BooleanField(verbose_name='Possui diabetes?')),
                ('hipertenso', models.BooleanField(verbose_name='É hipertenso?')),
                ('cardiaco', models.BooleanField(verbose_name='Tem doença cardíaca?')),
                ('intolerancia', models.BooleanField(verbose_name='Possui intolerância à lactose?')),
                ('remedio_especifico', models.BooleanField(verbose_name='Toma algum remédio específico?')),
                ('nome_remedios', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quais os remédios e horários?')),
                ('problema_saude', models.BooleanField(verbose_name='Tem algum diagnóstico de saúde física ou mental')),
                ('nome_probsaude', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qual diagnóstico de saúde física ou mental?')),
                ('telefones_urgencia', models.CharField(max_length=40, null=True, verbose_name='Telefones para urgência')),
                ('pessoa_convite_enct', models.CharField(max_length=40, null=True, verbose_name='Quem o convidou?')),
                ('telefone_pessoa_convite', models.CharField(max_length=40, null=True, verbose_name='Telefone do encontreiro')),
                ('desejo_participacao', models.TextField(null=True, verbose_name='Porque deseja participar do programa?')),
                ('pergunta_jesus', models.TextField(null=True, verbose_name='Quem é Jesus para você?')),
                ('tamanho_camisa', models.CharField(choices=[('P', 'P'), ('PP', 'PP'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=3)),
                ('observacoes_gerais', models.TextField(null=True, verbose_name='Observações Gerais')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Aguardando Pagamento'), (1, 'Concluída'), (2, 'Cancelada')], default=0, verbose_name='Situação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscrito em')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=40, verbose_name='nome_equipe')),
                ('qtd_participantes', models.IntegerField(null=True, verbose_name='qtd_participantes')),
                ('nome_casal_ligacao', models.CharField(max_length=100, verbose_name='nome_casal_ligacao')),
                ('encontreiros', models.ManyToManyField(related_name='encontreiros', to='core.Encontreiro')),
                ('nome_coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to='core.encontreiro')),
            ],
        ),
        migrations.CreateModel(
            name='Circulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_circulo', models.CharField(max_length=40, verbose_name='nome_circulo')),
                ('qtd_participantes', models.IntegerField(verbose_name='qtd_participantes')),
                ('cor_equipe', models.CharField(max_length=20, verbose_name='cor_equipe')),
                ('encontristas', models.ManyToManyField(to='core.Encontrista')),
                ('lider_circulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encontreiro')),
            ],
        ),
    ]
