# Generated by Django 2.2.7 on 2019-11-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Encontreiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, null=True, verbose_name='Nome')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('celular', models.CharField(max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('estado_civil', models.CharField(max_length=40, null=True, verbose_name='Estado civil')),
                ('facebook', models.CharField(max_length=50, null=True, verbose_name='Facebook')),
                ('cep_encontreiro', models.CharField(max_length=11, null=True, verbose_name='CEP')),
                ('naturalidade_encontreiro', models.CharField(max_length=40, null=True, verbose_name='Naturalidade')),
                ('logradouro_encontreiro', models.CharField(max_length=40, null=True, verbose_name='Logradouro')),
                ('numero_encontreiro', models.IntegerField(null=True, verbose_name='Numero')),
                ('complemento_encontreiro', models.CharField(max_length=60, null=True, verbose_name='Complemento')),
                ('bairro_encontreiro', models.CharField(max_length=25, null=True, verbose_name='Bairro')),
                ('estado_encontreiro', models.CharField(max_length=26, null=True, verbose_name='Estado')),
                ('cidade_encontreiro', models.CharField(max_length=30, null=True, verbose_name='Cidade')),
                ('frequentando_igreja_enc', models.CharField(max_length=5, null=True, verbose_name='Está frequentando a igreja?')),
                ('nome_igreja', models.CharField(max_length=50, null=True, verbose_name='Nome da igreja')),
                ('local_trabalho_enc', models.CharField(max_length=40, null=True, verbose_name='Local de trabalho')),
                ('escolaridade_enc', models.CharField(max_length=30, null=True, verbose_name='Escolaridade')),
                ('pessoa_convite_enc', models.CharField(max_length=30, null=True, verbose_name='Padrinho ou madrinha')),
                ('ano_participacao', models.IntegerField(null=True, verbose_name='Ano de participação')),
                ('equipes_trab', models.CharField(max_length=70, null=True, verbose_name='Equipes que já trabalhou')),
                ('curso_encontreiro', models.CharField(blank=True, max_length=70, null=True, verbose_name='Curso')),
                ('qtd_participacoes', models.IntegerField(null=True, verbose_name='Quantidade de participações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscrito em')),
            ],
        ),
        migrations.CreateModel(
            name='Encontrista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_apelido', models.CharField(max_length=60, null=True, verbose_name='Nome apelido')),
                ('data_nascimento_enc', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('celular', models.CharField(max_length=15, null=True, verbose_name='Celular')),
                ('estado_civil', models.CharField(max_length=40, null=True, verbose_name='Estado civil')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=40, null=True, verbose_name='Logradouro')),
                ('numero', models.IntegerField(null=True, verbose_name='Numero')),
                ('complemento', models.CharField(max_length=60, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=25, null=True, verbose_name='Bairro')),
                ('estado', models.CharField(max_length=4, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=30, null=True, verbose_name='Cidade')),
                ('naturalidade', models.CharField(max_length=40, null=True, verbose_name='Naturalidade')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('facebook', models.CharField(max_length=50, null=True, verbose_name='Facebook')),
                ('frequenta_igreja', models.CharField(max_length=5, null=True, verbose_name='Está frequentando alguma igreja?')),
                ('religiao', models.CharField(max_length=30, null=True, verbose_name='Religião')),
                ('nome_pai', models.CharField(max_length=60, null=True, verbose_name='Nome do pai')),
                ('religiao_pai', models.CharField(max_length=30, null=True, verbose_name='Religião do pai')),
                ('nome_mae', models.CharField(max_length=60, null=True, verbose_name='Nome da mãe')),
                ('religiao_mae', models.CharField(max_length=30, null=True, verbose_name='Religião da mãe')),
                ('possui_automovel', models.CharField(max_length=5, null=True, verbose_name='Possui automóvel?')),
                ('pessoas_moradia', models.CharField(max_length=60, null=True, verbose_name='Quem mora na mesma residência')),
                ('local_trabalho', models.CharField(max_length=40, null=True, verbose_name='Local de trabalho')),
                ('nome_escola', models.CharField(max_length=60, null=True, verbose_name='Nome da escola')),
                ('escolaridade', models.CharField(max_length=40, null=True, verbose_name='Escolaridade')),
                ('curso', models.CharField(max_length=50, null=True, verbose_name='Curso')),
                ('pessoas_participando', models.CharField(max_length=5, null=True, verbose_name='Algum conhecido participando do programa?')),
                ('nome_pessoas_participando', models.CharField(max_length=60, null=True, verbose_name='Nome das pessoas')),
                ('possui_probsaude', models.CharField(max_length=5, null=True, verbose_name='Possui algum problema de saúde?')),
                ('nome_probsaude', models.CharField(max_length=60, null=True, verbose_name='Qual problema de saúde')),
                ('telefones_urgencia', models.CharField(max_length=40, null=True, verbose_name='Telefones para urgência')),
                ('pessoa_convite_enct', models.CharField(max_length=40, null=True, verbose_name='Quem o convidou?')),
                ('telefone_pessoa_convite', models.CharField(max_length=40, null=True, verbose_name='Telefone do encontreiro')),
                ('desejo_participacao', models.TextField(null=True, verbose_name='Porque deseja participar do programa?')),
                ('pergunta_jesus', models.TextField(null=True, verbose_name='Quem é Jesus para você?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscrito em')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=40, verbose_name='nome_equipe')),
                ('qtd_participantes', models.IntegerField(null=True, verbose_name='qtd_participantes')),
                ('nome_casal_ligacao', models.CharField(max_length=40, verbose_name='nome_casal_ligacao')),
                ('encontreiros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encontreiros', to='core.Encontreiro')),
                ('nome_coordenador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to='core.Encontreiro')),
            ],
        ),
        migrations.CreateModel(
            name='Circulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_circulo', models.CharField(max_length=40, verbose_name='nome_circulo')),
                ('qtd_participantes', models.IntegerField(null=True, verbose_name='qtd_participantes')),
                ('cor_equipe', models.CharField(max_length=20, verbose_name='cor_equipe')),
                ('encontristas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Encontrista')),
                ('lider_circulo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Encontreiro')),
            ],
        ),
    ]
