# Generated by Django 2.2.7 on 2019-11-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191119_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='bairro_encontreiro',
            field=models.CharField(max_length=40, null=True, verbose_name='Bairro'),
        ),
    ]
