# Generated by Django 3.2.16 on 2022-12-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221214_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontrista',
            name='tamanho_camisa',
            field=models.CharField(choices=[('P', 'P'), ('PB', 'PB'), ('PP', 'PP'), ('PPB', 'PPB'), ('M', 'M'), ('MB', 'MB'), ('G', 'G'), ('GB', 'GB'), ('GG', 'GG'), ('GGB', 'GGB')], max_length=3),
        ),
    ]
