# Generated by Django 3.2.16 on 2022-12-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_encontrista_tamanho_camisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontrista',
            name='pergunta_jesus',
            field=models.TextField(blank=True, null=True, verbose_name='Quem é Jesus para você?'),
        ),
    ]
