# Generated by Django 2.2.7 on 2019-11-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191119_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='escolaridade_enc',
            field=models.CharField(max_length=40, null=True, verbose_name='Escolaridade'),
        ),
    ]
