# Generated by Django 2.2.7 on 2019-11-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191119_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='curso_encontreiro',
            field=models.CharField(max_length=70, null=True, verbose_name='Curso'),
        ),
    ]
