# Generated by Django 3.2.16 on 2022-12-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_encontrista_pergunta_jesus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
    ]
