# Generated by Django 2.2.7 on 2019-11-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191119_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='complemento_encontreiro',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='curso_encontreiro',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='escolaridade_enc',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='local_trabalho_enc',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Local de trabalho'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='local_trabalho',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Local de trabalho'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_escola',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome da escola'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_pessoas_participando',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome das pessoas'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_probsaude',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Qual problema de saúde'),
        ),
    ]
