# Generated by Django 2.2.7 on 2019-11-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191119_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='encontreiros',
        ),
        migrations.AddField(
            model_name='equipe',
            name='encontreiros',
            field=models.ManyToManyField(null=True, related_name='encontreiros', to='core.Encontreiro'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome_coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to='core.Encontreiro'),
        ),
    ]
