# Generated by Django 2.2.7 on 2019-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191120_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='encontreiros',
            field=models.ManyToManyField(related_name='encontreiros', to='core.Encontreiro'),
        ),
    ]
