# Generated by Django 2.2.7 on 2019-11-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191120_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulo',
            name='encontristas',
        ),
        migrations.AddField(
            model_name='circulo',
            name='encontristas',
            field=models.ManyToManyField(to='core.Encontrista'),
        ),
        migrations.AlterField(
            model_name='circulo',
            name='lider_circulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Encontreiro'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome_casal_ligacao',
            field=models.CharField(max_length=100, verbose_name='nome_casal_ligacao'),
        ),
    ]
