# Generated by Django 2.2.7 on 2019-11-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191120_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='status',
            field=models.IntegerField(blank=True, choices=[('Aguardando Pagamento', 'Aguardando Pagamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default=0, verbose_name='Situação'),
        ),
    ]
