# Generated by Django 2.2.7 on 2019-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191120_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook'),
        ),
    ]
