# Generated by Django 2.2.7 on 2019-11-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191120_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontrista',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao_mae',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Religião da mãe'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao_pai',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Religião do pai'),
        ),
    ]
