# Generated by Django 2.2.7 on 2019-11-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191120_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='naturalidade_encontreiro',
            field=models.CharField(max_length=50, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='naturalidade',
            field=models.CharField(max_length=50, null=True, verbose_name='Naturalidade'),
        ),
    ]
