# Generated by Django 2.2.7 on 2019-12-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191121_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontreiro',
            name='numero_encontreiro',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='pessoa_convite_enc',
            field=models.CharField(max_length=60, null=True, verbose_name='Padrinho ou madrinha'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='qtd_participacoes',
            field=models.CharField(max_length=20, null=True, verbose_name='Quantidade de participações'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='local_trabalho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local de trabalho'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_pessoas_participando',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome das pessoas'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='numero',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pessoas_moradia',
            field=models.CharField(max_length=70, null=True, verbose_name='Quem mora na mesma residência'),
        ),
        migrations.CreateModel(
            name='EquipeAzul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_participantes', models.IntegerField(null=True, verbose_name='qtd_participantes')),
                ('encontristas', models.ManyToManyField(to='core.Encontrista')),
                ('lider_circulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Encontreiro')),
            ],
        ),
    ]
