# Generated by Django 2.2.7 on 2019-12-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191211_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipeazul',
            name='lider_circulo',
        ),
        migrations.RemoveField(
            model_name='equipeazul',
            name='qtd_participantes',
        ),
        migrations.RemoveField(
            model_name='equipeazul',
            name='encontristas',
        ),
        migrations.AddField(
            model_name='equipeazul',
            name='encontristas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Encontrista'),
            preserve_default=False,
        ),
    ]
