# Generated by Django 2.2.7 on 2019-12-11 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191211_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipeazul',
            name='encontristas',
        ),
        migrations.AddField(
            model_name='equipeazul',
            name='encontristas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='encontrista', to='core.Encontrista'),
            preserve_default=False,
        ),
    ]
