# Generated by Django 2.2.7 on 2019-12-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191211_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipeazul',
            name='lider_circulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Encontreiro'),
        ),
    ]
