# Generated by Django 2.2.7 on 2019-12-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_equipeazul_lider_circulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipeazul',
            old_name='encontristas',
            new_name='encontrista',
        ),
    ]
